apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - backend.yaml
  - sites.yaml
  - routes.yaml
  # - hpa.yaml     # after uploads move to R2 (see backend.yaml)
