apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:jxc8R3pzSHcrSjTT/npdgE4Yp/AJp5YnQDiALGJijNO+r1R3K7L5l7Ds0JRCupDX3bghPaXUnU6zN9km69hjbg==,iv:X2a75BNEGlSI/4eG/OFO0Tz66dzDnpSrliWTb5/UDus=,tag:SYRiNk9yRzY6Lrovjf9bkQ==,type:str]
    admin-user: ENC[AES256_GCM,data:H7S9oB8WvTo=,iv:K6Oy/ppVW0HwOBR7GKyGkklB5AOYqH1l4ScyMzumDpg=,tag:JJ/cU50TuDY+H+X0D5sgcQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZWFTb3ByV09sMkYvQ1pj
            OHgrOTRRWUtlVkN5ZFFRS0pZYlY3NmxyY21nCmRleWxrSVkzS21NSExFNjVZV2lx
            MENObnprdE8wZ3BpaWsxcGU1NjVmUzgKLS0tIFVYUzc0TEY2ZG52bU9HdXFTc2RC
            eUJaNVFtaUg3aUNzdk12UDhLbHk3TDQKJm/q0h2cxPptyiP6O4+b/jN+4ltSkCk7
            6RWwf6RZjrfDu/lRqetK7cdhHlP/SoCSomJvfslrzda1RxgKH40ZWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15zx5lh9fe2r8ad3fm9vacu76jwe7hgs45ksmenwgfmjua5t7dstqj5x348
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:33:18Z"
    mac: ENC[AES256_GCM,data:qGYT4XcYVK6tWX4vkgjSWW0CtV+DwqZHzUZvenHqlz2sCNLXdF2SKepvGecnIHuJmfVZgP6fLbEbG7ueRCglJqwKUiEu5+0ROoiH8ijcD4XiP2R0yJbHwPvOJ6f9gfmNxxsLIosUgU/ZmjoBpMF2QMShUtU/5pBEv5WoN4NiHrQ=,iv:YM0KK85jsU0dMEZ6j6sHueiIPe8RnjEU4wn+OBHdJxA=,tag:kAQsmbFCNw67m78mQ29M6w==,type:str]
    version: 3.13.3
