apiVersion: v1
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:tj4JrXe3abnmUEf87XoGfX/Ilxn2f8WULHh8hvB8cRi1QmZ9XxBU1gSVrF2WKE3db543CV6idSKvGCi999gUnw==,iv:w2c9gLnQDTdZ5IeEs1BwbghgPZ93dpbaPiwxCfnQ6XQ=,tag:Nx7joSBqE431iCWZhF5urA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:xXZQYFwIeC6RhP/A,iv:UzmgfxZscnWq1AvbvOz1FLuk10Q/aEQ6XIi6Gp3gP8w=,tag:0uYxPco9HTAHoAfvB2D80A==,type:str]
kind: Secret
metadata:
    name: grafana-telegram
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZjgvSThTbWFHU3d4emxp
            OFcrSjN6MG82cWpVL0l3RmVKdURRSEloVlZNCk9CeGV6dmF6SEpVWC80MkhLenNR
            SDgyOTNVdmJURmpSSmxBT0RPTVhVTkEKLS0tIFk0cGhFU1VIbXhtK2hySnpxaDVT
            cXhzcmRsa1M5dVJzaWN2NE8wMnRZZUEK39GsDzmS4GExpvU0wGJpwtkXfzaFMRmf
            zFDrCuX88oilL0Pl+sI5NccaGkchwI75FjHvGvbhIBtr8BMjRQo+xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15zx5lh9fe2r8ad3fm9vacu76jwe7hgs45ksmenwgfmjua5t7dstqj5x348
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T16:59:06Z"
    mac: ENC[AES256_GCM,data:3BNq0+Hu/V/G94KoIbCc7HpNZx53RG6eVq0lzMcQQyGNGromwI7H2G4cuEyFFJQfTyLOJpyhxhTAEJwx9kW65rxidvYO7WrVoPGwSk7C1U3WmwjqWhQmA/WRz7YHmEZLYD5lAOn1RKDUSt8z36rB54GHF2F8b83V+pn8fn61yB8=,iv:zSBmaqUACcZAT+hvOUrXbmQGCOmAG95P6JfuqeHV+Y4=,tag:A9O6uTzEmGNKpESUyQew0w==,type:str]
    version: 3.13.3
