apiVersion: v1
data:
    password: ENC[AES256_GCM,data:gqpsVHvwo8fQzQYMcVg969DqgIWWkqWn4O3GJYSdf/ONk7GZIXCiEap+T+4HgAR29BCJVZ4IxI/dWVTj8f6ftQ==,iv:QcR0YKk8oupq09tFF0Ikv4QMRxGXwkE0rifhFDlWUNM=,tag:ROl7njntGP3nLwLBv3/l3Q==,type:str]
    username: ENC[AES256_GCM,data:ru/QMOjGfJA=,iv:+kZeayEUZV6mH8Vj3pUJX1xjgUzmWFDVJUWtsjK4VWo=,tag:SX1whLxTi8zJyEiZwOArYQ==,type:str]
kind: Secret
metadata:
    name: pg-game-kelime
    namespace: game
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieUJxVzkrM2hwektDMGpE
            bmhaN2pwc3pxcmhGcXVYSzRENFRBanJsR1d3CkNCOE5UTit4VHd2VjA4RkJpYWti
            Qm0rdGFEZ29WVmQremFrSk5tTmVsVnMKLS0tIE9XQ1ZBa3g3eGxzUmY5bHlSSU1D
            MVNWN2JFWWpxTVhIaG9ZYTRwWHkxcXMKKin3sh3+3w9hymHxu5sBLdwgLCvb0s65
            HbSmvAecD2ikpfxblJIIq664vhtuJgQg9p+OySzjW9lLa6N0PZzXIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15zx5lh9fe2r8ad3fm9vacu76jwe7hgs45ksmenwgfmjua5t7dstqj5x348
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:33:17Z"
    mac: ENC[AES256_GCM,data:+BY1dRpchZWHt87pKurd/G9ewJycUYkZc5LXMgsKkkCP6/5EIh4rX3i0cHnYXkqo6FSzvhkSIkGFTrpwJNXdVJkJIv+G1F5BlXj8ZwD2sD7fouaz8a0pL6W18VLbdvfDhIX8p7sNPz4N+nnnwkoMjTChQdH1Id7zoDaWaoS4baY=,iv:lPJqtEBowsq+B2M9+IzEE0ao+rDzHLSz1nUIDDBLnqQ=,tag:64CD1Fjm8lyTLy4mAwctUQ==,type:str]
    version: 3.13.3
