apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:9vTALm4sflYyqayOFpGSgU8BuvcjEi3uv5UIK8PyYjcvaj3+ww/oJTqLax0=,iv:CweVKFHE1z95xfEmb6kbd2r2vn0HIR+nBllrBV7XbJQ=,tag:0e0B968tAyyb2AJKfF3jTA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:tj3uU07PdyaCtmMHRHumZ+JzDMi9wxDil6/NeoOBkyb5RjHl5/xO89MnY+DJE/1TgmiEo5y8ad2omR+OmbKfaG9S3QVbdu20uZH8Brg2QoyWg6qjJFoKFQ==,iv:uSaP5TisFtC+Qbh1v5pScoYd6g1U2JkToTDJrSJvKhU=,tag:c5zU0oa4NoLlZZmo5rD7fQ==,type:str]
    REGION: ENC[AES256_GCM,data:I5UFZZ5Lj5o=,iv:aJjxCZnXEKeo4zuLM+kas90uAoz/9iXWDs3UTNieJ1E=,tag:lc+qXrUS5cOOQt3N8FUIaQ==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: game
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWEF1ZHUzMHZLYVVnVjd6
            VlFoTy91VkJHSnRPVkdmc0RDUzIzeFBESlZZCkM3TGtXTDNPZHJCQ1ZXVWVYcEJH
            bjZZT3RsZUhlSzZGVm9Kc0JodGUxTFkKLS0tIGU4R0hqNVB1TUVlNFNFOW9OdVdq
            OWJGTjl6OHBycEp6akJpd2NTL1FQWWMKK+lVBGoNfCirePaEkc/WnXQHylZ9CQuB
            JS3F6fbrz5GiKPCeNgFg4DajKEX1h1XNigvCz+ifZeDm8fcCFouHJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15zx5lh9fe2r8ad3fm9vacu76jwe7hgs45ksmenwgfmjua5t7dstqj5x348
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:35:06Z"
    mac: ENC[AES256_GCM,data:5wJ6dY4TWf1rrxUjcTpAPFXUQO+xhXWSxuUaTIwAsol01I7uYQCN3AJC8bYBTGwE04G7L8UI6EE4jkBZMK7XyjdN7oOMWLfbrAEpoInowwGgJXsioYn8tKfEp3ZVV/cE+VrllsjgSipmh8gXOYpsYbgatL+0evU5y5L+68ditss=,iv:eZZz2tat5Ec3DLVD9o29DibCnjsDENUVjjHRg0XFbl4=,tag:JG5IlCXuIiZ26mFH22hZ/w==,type:str]
    version: 3.13.3
