apiVersion: v1
data:
    CHAT_MODEL: ENC[AES256_GCM,data:ae+mm2E2+pSBIS/iaRmDhQ==,iv:XhASXJmLKDP5sKCXIP//D8ED8VRf6oJX/o+IUgWMHPo=,tag:bET+gtyUhqqorA2MxAiUMw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0pDxEBGhOmRbV9IvlbPzYbH0W+s0tXQp29we7C/IhXb8x3v9t7aIOquVCwGmNeZ8c/ZuKnAIWay5LO/aizKb66WaaX9iNFkhxt9eTWWZQ5KYS6/t/CDRw20Ej86hyyx+wxF0hlvPCAN+PTcFdQFQJ0RAo5Sa//v04JO8DCK4gLSI3AJhFrCnlK2YIBZ0XWov,iv:oGvIAQpkksARV0wMU3MRpg6dAaAnjZ+VTZfzef8pWZw=,tag:vlPhIeEMc4HkCbXzVV5K2Q==,type:str]
    EMBEDDING_MODEL: ENC[AES256_GCM,data:H+JjbQAU94Zuf5AxAQEcP3NIF09jsuq705aO68YCdjM=,iv:KNYLDY65/dgKob3xDOq9Spm/UfI42BhUqLHoyG3kw4s=,tag:DGG2aP2AMvGHexzf7DbxrA==,type:str]
    MIN_SCORE: ENC[AES256_GCM,data:g7mVjJYLrFs=,iv:yuOqW/cg24lvwaakNVVto5X70LbU4FDS4SibvH8CxlY=,tag:l/j/hRE65hz4VeKkAvuspA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:m6q6bVKufv8LVmHV+ZYokeCf96seDa1KnAhtaWl2+iBBTC1abA7BPqKzimW/Hl6+ZHFbmayqvZ4aDLfype0qrqj1nK5Blxe3MMxGW5Fy8HZJ13gJEcSJHAMtlvaAnNC19sirQlJIR33dQX/LuecMR2s+XuWY9vW0En0g6lB51h/PTdP1EL0qDzSJhHJ/GQ7OuUnaI/SsnAWSUKNwpVNYja54EQVzofmgeOk3maS3ol9d+/47/fFJb7Cb9BYKdTeb13uV2/QadD4HKOyDN7V7rNk8HbTq3cMmC5v7+g==,iv:zN9c6s9O914yYZcWCXajT7+qTJHtJvoZ7wpKh50IvUM=,tag:AphKrmL5XLvGVaB4Rus1Fg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:mjMHRurFvlyUYSkiE/AIob/sPcUz3dslrmOgsqBg/j+ue9/1I2H9zF/cnd8xNEQVPKfJgdS+mVFrGpep8fMV8IguNkrnXCE11bps651JIBPpgvhEOm6U6A==,iv:l2gckl9feXBPl34waIcKppzap7mzOJ8G75O2PKB/FxE=,tag:kRMBtdxCQAvuNUn41kbwzw==,type:str]
    SUPERADMIN_EMAIL: ENC[AES256_GCM,data:HQtsnSBLO5BuyQT+9W4gxXxIbVEmC1wiXAU2D+GrLzg=,iv:rmCS6OV5/daEX1PPWzlh+gOBeraMk5zEdeGw84RYiLo=,tag:CVBql6x2p1olDzDcKxzFcA==,type:str]
    SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:KVqy0zlSZhUgvZaH50b2EcqeuDBsc5ng,iv:lGGlkuuSZf8++a09zfwtsXuCRA0vyLg95ywkcGP1swQ=,tag:NNGKcBnnh6I7LGM/UmhT+g==,type:str]
kind: Secret
metadata:
    name: assist-env
    namespace: assist
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUnVtRHVLby9VM3IyRFFP
            K1JON0FmdDZPR3lybFI0UlZHa29uTGtwUnhvCmd1TGh1UkV2QVhpM1ptVkpQU08z
            amVjVWVueEN2MGdDdDVhNkpxQUNLcm8KLS0tIDJXK3FBZXF5em5NNVl2N1d6d1Zt
            dGJXek1nN0Y2SndpYi9wVUJTenZVQ2cK2ep0lY47Kxsf/FzB4UYqDQ3bGcaoULsc
            oRzAWB7baWQpJWIttd/TBB+H8PwzGUE8GbxrQlBQ2VrMerDyTPmLDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15zx5lh9fe2r8ad3fm9vacu76jwe7hgs45ksmenwgfmjua5t7dstqj5x348
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T13:20:49Z"
    mac: ENC[AES256_GCM,data:QQNW85A1aYwOwRaCPfWV+OnQf4CJUdkYYNL146srFM7X0p/AxAKeV1uXqq9v3ve7Mt4V2cX3dOPklbEwH3mvN6twc8EYy49d+9wfNOpBisl5J+vCBGRjItB0xNPb4212K6/LEinig5Tz0biLKBbctMODGMr+HS63/rsLTSXen5o=,iv:gNujdMBx5qSMLS6YjKXYPG01ziEJyjpmbtmULrg35OU=,tag:2T3CKs6+gkNX/LMVtmLgWg==,type:str]
    version: 3.13.3
